version: '3.2'

services:
  mariadb:
    image: mariadb:10.5.8
    container_name: boilerplate_mariadb
    restart: always
    networks:
      - app-network
    ports:
      - 3306:3306
    volumes:
      - ../mariadb/data:/var/lib/mysql
      - ../mariadb/conf/mariadb.cnf:/etc/mysql/my.cnf
    env_file:
      - ../.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MARIADB_DEFAULT_DATABASE}
      TZ: ${MARIADB_TIME_ZONE}

  nestjs:
    image: boilerplate_nestjs
    container_name: boilerplate_nestjs
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.dev
    restart: always
    depends_on:
      - mariadb
    networks:
      - app-network
    volumes:
      - ../src:/app/src
      - ../node_modules:/app/node_modules
    env_file:
      - ../.env
    ports:
      - 5000:5000

networks:
  app-network:
    driver: bridge
